#!/bin/bash

plot_results() {

blockmean sigma_c.dat $R  -I6m -V > sigma_r.dat
surface sigma_r.dat  -Ggm0.grd -I2m  -R -T0.2
grdraster 9 $R -I2m -Gout.grd
grdgradient out.grd -A0 -Nt -Gtopo.grd
psbasemap $R $J -Ba4f2/a4f2WSen -K -V -X2.0 -Y2.0i -P > $M
makecpt -Chaxby -I $T -Z > vel.cpt
grdimage gm0.grd  -Itopo.grd -Cvel.cpt  -R -J -O -V -K >> $M
grdcontour gm0.grd  -R -J -Cvel.cpt -B  -A-  -O -K -S6m -V >> $M
psxy edge_location.txt -R -J -O -K -G255 -L -W1 -V >> $M 
pscoast -Jm -R  -S248/248/255 -B -N2 -W4.0 -A5000  -O  -V -K >> $M
#awk '{printf "-77 29 15 0 1 BL Period:%.0fs",1/$1}' ../freq_one > time.dat
#pstext time.dat -R -J -P -O -K -V >> $M
psscale -Cvel.cpt -D2.2i/-0.5i/3.48i/0.2ih -O -B$text1:"$text2":/:"$text3": -E >> $M 

}

#set up R J parameter
R=`minmax -C st.txt | awk '{printf "-R%.f\/%.f\/%.f\/%.f\n",$1-4,$2+4,$3-2,$4+2}'`
J="-Jm0.5"

#plot geometrical spreading
awk '{if($5>=-5 && $5<=5 && $5!=0) print $1,$2,$5}' azi_rad_geo_all > sigma_c.dat
M=`awk -F_ '{printf "geometrical_spreading_%.0fs.ps",$1}' ../period`
T="-T-5/5/1"
text1=""
text2="Geometrical spreading"
text3="1/1000km"
plot_results
