#!/bin/bash

plot_strain() {

blockmean sigma_c.dat $R   -I2m -V > sigma_r.dat
surface sigma_r.dat  -Ggm0.grd -I2m  $R -T0.2
grdraster 9 $R -I2m -Gout.grd
grdgradient out.grd -A0 -Nt -Gtopo.grd
psbasemap $R $J -Ba4f2/a4f2WSen  -K -V -X2.0 -Y2.0i -P > $M
makecpt -Chaxby  $T -Z > $CPT
grdimage gm0.grd -Itopo.grd -C$CPT  $R $J -O -V -K >> $M 
grdcontour gm0.grd $R $J -C$CPT -B  -A-  -O -K -S6m -V >> $M
psxy  edge_location.txt $R $J -O -K -G255 -L -W1 -V >>$M
psxy tecton_bound.gmt -m -R -J -O -K -W1.5p,red >> $M
pstext nam_labels.dat -R -J -O -K -V >> $M
awk -F_ '{printf "-122 29 15 0 1 BL Period: %.0fs",$1}' ../period > time.dat
pscoast -Jm -R  -S248/248/255 -B -N2 -W4.0 -A5000  -O  -V -K >> $M
pstext time.dat -R -J -P -O -K -V >> $M
psscale -C$CPT -D2.5i/-0.5i/3.8i/0.3ih -B:"Focusing/defocusing correction":/:"10^-3 sec/km^2": -O -E >>$M
}

paste st.txt dyna_pxpy > loc_B 
awk 'function abs(x){return ((x < 0.0) ? -x : x)} {printf "%f\n%f\n",abs($3),abs($4)}' loc_B > B_all
percentage=`minmax -C B_all | awk  '{print $2*0.005}'`
damping=`minmax -C B_all | awk  '{print ($2*0.04/6.371)^2}'`
awk -v a=$percentage 'BEGIN {print "lon lat Ve Vn Se Sn Cen Site Ref"} {print $1,$2,$3,$4,a,a,"0.05 stat(0,0) test1"}' loc_B > GPS_raw.dat
process_AB $damping
awk '{if($3<0.8 && $3>-0.8) print}' sigma_c.dat > 1
mv 1 sigma_c.dat
M=`awk -F_ '{printf "focusing_%.0fs.ps",$1}' ../period`
R="-R-125/-97/27/50"
J="-Jm0.5"
T="-T-0.8/0.8/0.2"
CPT="shear2.cpt"
S="-Se15/0.95/0"
plot_strain

rm .gmt*
