#!/bin/bash

plot_strain() {

blockmean sigma_c.dat $R   -I2m -V > sigma_r.dat
surface sigma_r.dat  -Ggm0.grd -I2m  $R -T0.2
grdraster 9 $R -I2m -Gout.grd
grdgradient out.grd -A0 -Nt -Gtopo.grd
psbasemap $R $J -Ba4f2/a4f2WSen  -K -V -X2.0 -Y2.0i -P > $M
makecpt -Chaxby  $T -Z > $CPT
grdimage gm0.grd -Itopo.grd -C$CPT  $R $J -O -V -K >> $M 
grdcontour gm0.grd $R $J -C0.5 -B  -A-  -O -K -S6m -V >> $M
psxy  edge_location.txt $R $J -O -K -G255 -L -W1 -V >>$M
#psxy tecton_bound.gmt -m -R -J -O -K -W1.5p,red >> $M
#pstext nam_labels.dat -R -J -O -K -V >> $M
awk -F_ '{printf "-122 29 15 0 1 BL Period: %.0fs",$1}' ../period > time.dat
pscoast -Jm -R  -S248/248/255 -B -N2 -W4.0 -A5000  -O  -V -K >> $M
pstext time.dat -R -J -P -O -K -V >> $M
psscale -C$CPT -D2.5i/-0.5i/3.8i/0.3ih  -B:"$H":/:"10^-3 sec/km^2": -O -E >>$M
}

#plot apparent amplification factor
awk '{if($3>-1 && $3<1) print}' appa_amp > sigma_c.dat
M=`awk -F_ '{printf "amp_decay_appa_%.0fs.ps",$1}' ../period`
H="Apparent amplitude decay"
R=`minmax -C st.txt | awk '{printf "-R%.f\/%.f\/%.f\/%.f\n",$1-4,$2+4,$3-2,$4+2}'`
J="-Jm0.5"
T="-T-1/1/0.2"
CPT="shear2.cpt"
S="-Se15/0.95/0"
plot_strain

#plot focusing/defocusing
awk '{if($3<1 && $3>-1) print}' focusing_amp > sigma_c.dat
M=`awk -F_ '{printf "amp_decay_focusing_%.0fs.ps",$1}' ../period`
H="Focusing/defocusing correction"
plot_strain

#plot corrceted amplitfication factor
awk '{if($4<1 && $4>-1) print $1,$2,$4}' azi_amp_stru_velo > sigma_c.dat
M=`awk -F_ '{printf "amp_decay_corrected_%.0fs.ps",$1}' ../period`
H="Corrected amplitude decay"
plot_strain


paste appa_amp focusing_amp | awk '{print $1,$2,$3,$6}' > appa_focusing.dat
appa_focus_correlation.py

mv amp*ps ../plots
rm .gmt*
