#!/bin/bash

make_sparse_geometry                              # run sparse version of make_geometry

make_raw_spline_fit_dat				# above steps are commented out for now

make_x_for_fit_wg<<!
0 0 0
!

make_null_input_with_variance_wg<<!
$1
0.25
!

process_prepare_gps_AB
cp latlong_gps.dat output.dat || exit 1
awk '{if(NR==1) print $1}' latlong_gps.dat > nout.dat

make_x_for_output_wg<<!
0 0 0
!			

make_x_for_fit_wg<<!
0 0 0
!
                                     
sparse_fit_with_GPS_wg<<!
N
Y
N
!
sparse_velocity_wg<<!
Y
0 0 0
!

sparse_strain_wg<<!
Y
!
strain_cont_asia2
sparse_rotation_solution<<!
Y
0 0 0
!

gps_rotation_sparse

velocity_diff -o GPS_rotated.out -m velocity.out -e 1 > stat.out

prepare_regular_lat_long<<!
0 0 0
5
$2 $3 $4 $5
$6 $7
!

cp regular_lat_long.dat output.dat

make_x_for_output_wg<<!
0 0 0
!

sparse_velocity_wg<<!
Y
0 0 0 
!

velocity

sparse_strain_wg<<!
Y
!
