#!/bin/csh
#source -44.6219     26.5904  located in the atlantic ocean: Northern Mid-Atlantic Ridge
#station  -123.602  42.156


convert_lat_long<<!
0 0 0
15
profile_lat_long.out
!

cp lat_long.dat output.dat

make_x_for_output_wg<<!
0 0 0
!

sparse_strain_wg<<!
Y
N
!

sparse_velocity_wg<<!
Y
N
0 0 0
!

velocity
